### ISSUE TITLE
"The account being accessed does not support http" hasn't fixed

### ISSUE THREAD

**Issue by kulmam92** [rundeck-plugins/rundeck-azure-plugin#14]
I'm still having the same issue as #11  even though I'm using azure-plugin-1.0.5.jar

`ERROR LogFileStorageService --- [eduler_Worker-1] Failed to initialize LogFileStoragePlugin 'azure-storage': com.microsoft.azure.storage.StorageException: The account being accessed does not support http.`

Would you doublecheck if the fix is working?

**Comment by gbnord** [comment]
@kulmam92 
Try to add:
framework.plugin.ExecutionFileStorage.azure-storage.defaultEndpointProtocol=https
in framework.properties.
It worked for me.

**Comment by ltamaster** [comment]
@kulmam92   `framework.plugin.ExecutionFileStorage.azure-storage.defaultEndpointProtocol=https` should work
tat was included here https://github.com/rundeck-plugins/rundeck-azure-plugin/pull/12
Please let me know if worked
