### ISSUE TITLE
how you define environment variables and values azure blob storage 

### ISSUE THREAD

**Issue by arcxda** [rundeck-plugins/rundeck-azure-plugin#15]
it is very understandable variables for Amazon S3, which would be its similar for this Azure Blob Storage Plugin in the manifest of the rundeck deploy on kubernetes

name: RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_NAME
          value: "com.rundeck.rundeckpro.amazon-s3"
        - name: RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_S3_BUCKET
          value: "rundeck"
        - name: RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_S3_REGION
          value: "us-east-2"
        - name: RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_S3_ENDPOINT
          value: "http://minio.default.svc.cluster.local:9000"
        - name: RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_S3_PATHSTYLE
          value: "true"
        - name: AWS_ACCESS_KEY_ID

**Comment by arcxda** [comment]
@ltamaster

**Comment by ltamaster** [comment]
Hi, 
for docker you need to create a custom template 
here is an example https://github.com/rundeck/docker-zoo/tree/master/config
Rundeck docker uses a template system to generate configurations from environment variables
